# Generated by Django 3.2.9 on 2021-11-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhPho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DuLieu_ThoiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoigian', models.DateField()),
                ('nhietdocaonhat', models.FloatField()),
                ('nhietdothapnhat', models.FloatField()),
                ('doam', models.FloatField()),
                ('luongmua', models.FloatField()),
                ('tocdogio', models.FloatField()),
                ('id_thanhpho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.thanhpho')),
            ],
        ),
    ]
